export const channels = Object.freeze({
  health: 'cache-manager:health',
  initialState: 'cache-manager:initial-state',
  settingsGet: 'cache-manager:settings:get',
  settingsUpdate: 'cache-manager:settings:update',
  chooseRoot: 'cache-manager:dialog:root',
  scan: 'cache-manager:scan',
  cancel: 'cache-manager:cancel',
  search: 'cache-manager:search',
  cacheDetails: 'cache-manager:cache:details',
  cacheDetailsCancel: 'cache-manager:cache:details:cancel',
  storageGet: 'cache-manager:storage:get',
  artifactsCleanup: 'cache-manager:artifacts:cleanup',
  artifactsClear: 'cache-manager:artifacts:clear',
  artifactsOpen: 'cache-manager:artifacts:open',
  trashMove: 'cache-manager:trash:move',
  trashList: 'cache-manager:trash:list',
  trashRestore: 'cache-manager:trash:restore',
  trashPurge: 'cache-manager:trash:purge',
  play: 'cache-manager:play',
  exportMedia: 'cache-manager:export:media',
  exportDiagnostics: 'cache-manager:export:diagnostics',
  desktopInfo: 'cache-manager:desktop-info',
  progress: 'cache-manager:event:progress',
  unavailable: 'cache-manager:event:unavailable',
});
